### ISSUE TITLE
Stuck on choose voicing.

### ISSUE THREAD

**Issue by RannyBergamotte** [znarf94/MuseScore_Barbershop_Harmonizer#1]
So in Musescore, I selected the root and chord that I wanted, and then when I went to choose voicing, and tried to click, nothing happened, apart from putting the chord name on top. I thought the plugin would fill out the other voices for me?

Hopefully I'm not misunderstanding anything.

**Comment by znarf94** [comment]
Hi !
That's true, I forgot to mention in the documentation that the plugin currently does not add notes to the score, it only changes the pitch of existing accompanying notes.

So if you have a single note on voice #2 like this, nothing is inserted:
![image](https://user-images.githubusercontent.com/3353107/167728426-85ad6623-13c4-4161-a4db-0581c8d5c0e8.png)

But if there are already some notes on voices 1, 3 and 4, like this:
![image](https://user-images.githubusercontent.com/3353107/167728736-9f303cc8-df3b-416e-8fdf-678a5dc58bb8.png)

When you click on a voicing, the notes are updated:
![image](https://user-images.githubusercontent.com/3353107/167728938-d4c30834-2c20-493c-9d6b-1e38bb0a68fc.png)

I remember that adding notes from a plugin is more complex than just changing pitches, but I hope I'll manage to implement it some day.

**Comment by RannyBergamotte** [comment]
Ahhh ok that makes sense now! Thank you so much! 

Plugin is amazing btw, love it :)

**Comment by znarf94** [comment]
You're welcome, thanks for your feedback
